### ISSUE TITLE
Camera does not move

### ISSUE THREAD

**Issue by mzahana** [Jaeyoung-Lim/mavros_humantracking#10]
Hi @Jaeyoung-Lim I am trying to control camera gimbal using `/mavros/mount_control/command` mavros topic.

I published,
```sh
rostopic pub --once /mavros/mount_control/command mavros_msgs/MountControl "header:  
  seq: 0                    
  stamp: {secs: 0, nsecs: 0}
  frame_id: 'map'
mode: 2
pitch: -1.0
roll: 0.0
yaw: 0.0
altitude: 0.0
latitude: 0.0
longitude: 0.0"
```

However, the camera in Gazebo didn't move. Do I need to to do something else? e.g. setting some PX4 parameters?
I am using mavros installed using `apt-get` and PX4 v1.10.1

**Comment by Jaeyoung-Lim** [comment]
@mzahana Are you saying that this package is broken?

why are you trying to manually publish topics?

I think the gimbal only moves in auto mode

**Comment by mzahana** [comment]
I have not tested the package. I was just looking at how you control the gimbal from ROS.

Anyway, I found the issue. I was sending small values in radians while it should be in degrees and that's why it was not noticable. Also, the vehicle has to be armed.
