### ISSUE TITLE
Readme file must be improved

### ISSUE THREAD

**Issue by sahin52** [Jaeyoung-Lim/mavros_humantracking#15]
The written details are not enough to launch the package.

**Comment by Jaeyoung-Lim** [comment]
@sahin52 Thanks for the feedback

What more information do yoi need? Can you help improve the documentation?

**Comment by sahin52** [comment]
I couldn't understand how to make the project. catkin_make didnt work. I couldnt find a makefile either. Could you please tell how to use the project? I am new to Ros, Mavros, Px4 etc. So, sorry if the problem is about me.

**Comment by Jaeyoung-Lim** [comment]
@sahin52 If you understand how to use ROS, it should be quite straight forward, since some people are using this repo without any issues.

You should copy this project into your catkin workspace, and run
```
catkin build
```

**Comment by sahin52** [comment]
Thanks

**Comment by Jaeyoung-Lim** [comment]
@sahin52 Are those instructions enough for you?

**Comment by sahin52** [comment]
Yes, thanks
